### ISSUE TITLE
addFields: required option

### ISSUE THREAD

**Issue by diezmilseres** [steirico/kirby-plugin-custom-add-fields#10]
```
  nomenclador:
    label: Seleccione
    type: multiselect
    required: true **-->>> not working, its create the page bypassing this option**
    layout: list
    separator: ;
    options: query
    min: 1
    max: 1
    query:
      fetch: site.find('nomencladores').drafts
      text: "{{ page.description }}"
      value: "{{ page.title }}"
```
