### ISSUE TITLE
Fields always appear in alphabetical order

### ISSUE THREAD

**Issue by chrispymm** [steirico/kirby-plugin-custom-add-fields#11]
As far as I can see when using the addFields section in a blueprint, the fields in the modal always appear in alphabetical order by name of the field.  Is this the expected/desired behaviour?

Below is my blueprint:

```yml
addFields:
  title:
    label: Title
    type: text
    required: true
    icon: title
  network:
    label: Network
    type: select
    required: true
    options: query
    query: kirby.collection("networks")
    icon: globe
  slug:
    label: URL appendix
    type: text
    required: true
    icon: url
```

And the screenshot in the panel:

![image](https://user-images.githubusercontent.com/595564/67576742-09221000-f737-11e9-9a6d-89e787422e87.png)

I'd expect the fields to appear in the order defined in the blueprint.  Am I doing something wrong? Thanks
