### ISSUE TITLE
Skipping doesn't work

### ISSUE THREAD

**Issue by nilshoerrmann** [steirico/kirby-plugin-custom-add-fields#23]
I'm using this plugin to skip the create page dialog for a specific page type. If I hit the "add page" button, I get his dialog:

<img width="547" alt="grafik" src="https://user-images.githubusercontent.com/25466/77050267-cd2f6600-69c9-11ea-9961-1f2869178c72.png">

There are no logs in the console.

This is the blueprint:

```yml
title: Wochendienste
addFields:
  __dialog:
    skip: true
    forcedTemplate: service
columns:
  primary:
    width: 2/3
    sections:
      published:
        type: pages
        headline: Veröffentlicht
        status: published
  secondary:
    width: 1/3
    sections:
      drafts:
        type: pages
        headline: Entwürfe
        status: draft
        limit: 5
```

This is what the API responds:

```js
{
    "page": {
        "content": {
            "title": 1584608856
        },
        "slug": 1584608856,
        "template": "service"
    },
    "skipDialog": true
}
```

While this looks correct, no page is created on disk, no redirect happens.

**Comment by steirico** [comment]
Sorry for the late reply.

Basically, the properties `skip` and `forcedTemplate` control how parent pages/blueprints behave when adding subpages.

Let's say there is a blueprint called `service-list` and you intend to add pages based on blueprint `service` and skipping the add dialog. Then these properties have to be set on `service-list`.  

For further assistance: Does the presented blueprint correspond to `service.yml`? What is the intended hierarchy of the pages/blueprints?

**Comment by nilshoerrmann** [comment]
Thanks for you feedback!

We've got two blueprints, `services` (the list view) and `service` (the page view):

### `services.yml`

```yml
title: Wochendienste
addFields:
  title:
    label: Titel
    type: text
    required: false
    icon: title
  __dialog:
    redirect: true
    skip: true
    forcedTemplate: service
columns:
  primary:
    width: 2/3
    sections:
      published:
        type: pages
        headline: Veröffentlicht
        status: published
  secondary:
    width: 1/3
    sections:
      drafts:
        type: pages
        headline: Entwürfe
        status: draft
        limit: 5
        templates: service
```

### `service.yml`

```yml
title: Wochendienst
fields:
  week:
    type: multiselect
    label: Kalenderwoche
    width: 2/3
    max: 1
    options: api
    api:
      url: "{{ kirby.url }}/fetch/weeks"
      fetch: weeks
  family:
    type: pages
    label: Familie
    width: 1/3
    query: site.find('kontakte')
```

> Then these properties have to be set on service-list.

I thought to have done that by setting `templates: service` on my pages section. Is there another spot I've missed?
