### ISSUE TITLE
Error message when saving a draft

### ISSUE THREAD

**Issue by MikeHarrison** [steirico/kirby-plugin-custom-add-fields#46]
Hi,

I have installed the plugin, and started working out how to use it to create custom slugs for my pages. I currently have this set in my template:

```
addFields:
  title:
    label: Title
    type: text
    required: true
    icon: title
  startDate:
    type: date
    label: Start date & time
    time: true
    required: true
```

And when I click to add a page the correct fields are appearing. However when I click `Create Draft` I am getting the following error message:

**method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given**

The draft is created correctly, but something isn't working quite right. If you have any insight that would be great
