### ISSUE TITLE
Default Values not loaded

### ISSUE THREAD

**Issue by hariom147** [steirico/kirby-plugin-custom-add-fields#55]
**First of all: Thanks for this great plugin and for updating it to Kirby 3.6!**
I noticed that default values are not loaded into the fields, when opening the page add dialog.
I have the following code in blueprints, but neither is the date set to `now` (current date) nor is the toggle field set to `true` (on).
```
addFields:
  date:
    label: Datum
    type: date
    default: now
    width: 2/3
    required: true
    help: "{{page.date.toDate('l')}}"
  templatetoggle:
    label: ohne Vorlage
    type: toggle
    width: 1/3
    default: true
```
