### ISSUE TITLE
Date Field is Broken

### ISSUE THREAD

**Issue by Jayshua** [steirico/kirby-plugin-custom-add-fields#9]
Looks like the date field's calendar widget doesn't work inside the add dialog. Also, I would have expected it to be on top of the dialog, not inside and cut off by the bottom of the dialog.

![image](https://user-images.githubusercontent.com/1654103/60116710-2f5e8180-973e-11e9-826a-0c4fbf5e565d.png)

**Comment by Jayshua** [comment]
Oh, and this was current version of Firefox with Kirby 3.1.3.

**Comment by steirico** [comment]
Could you provide the `addFields` part of the corresponding blueprint, please? Furthermore, is it then a site or a page blueprint?

**Comment by Jayshua** [comment]
This is a page blueprint.

```
addFields:
  city:
    label: City
    type: text
    required: true
    icon: circle-outline

  date:
    label: Date
    type: date
    required: true
    icon: calendar

  title:
    label: Title
    type: text
    required: true
    icon: title
```

**Comment by steirico** [comment]
Let's tear down this issue into two separated points:

1. The date field's calendar widget doesn't work inside the add dialog
2. Calendar widget's bottom part is hidden behind the dialog's buttons

Unfortunately, I was not able to reproduce (1) using [Starterkit](https://github.com/getkirby/starterkit) with kirby 3.1.3, the plugin installed by composer, using the provided add fields and testing in Firefox 67.0.4 on macOS. There might be a correlation with another plugin or custom CSS in the panel.

(2) is related to kirby's underlying [k-dialog](https://getkirby.com/docs/reference/plugins/ui/dialog) widget and the way [overflows are handled](https://github.com/getkirby/kirby/blob/80b69380e672565a849037232c9951d1e32774c8/panel/src/components/Dialogs/Dialog.vue#L233). I will file an issue to kirby in order to discuss the use case in this issue.

In the meantime you can get around (2) by the adding `index.css` to the plugin's folder and add the following content:
```css
.k-dialog-body {
  overflow: visible;
}
```
